### ISSUE TITLE
Site throws a 404 error but runs fine localy

### ISSUE THREAD

**Issue by SuperZekes** [Fabulously-Optimized/mrpack-to-zip#2]
I still have a copy may I use your source and style the website in my own way to avoid redistribution?

**Comment by Madis0** [comment]
The link is now fixed. You are always free to fork it [according to the license](https://github.com/Fabulously-Optimized/mrpack-to-zip/blob/main/LICENSE).

**Comment by SuperZekes** [comment]
Thanks! This tool is helpful for those who don't Modrinth App
